name: Build script

on:
  push:
  workflow_dispatch:
    inputs:
      revision:
        description: "Revision to build"
        required: false
        default: ""
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Revision to build is ${{ inputs.revision }}"

      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.revision }}

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - run: npm ci
      - run: npm run build

      - uses: actions/upload-artifact@v4
        with:
          name: issue_templates.${{ github.sha }}.js
          path: assets/javascripts/issue_templates.js
          compression-level: 0
