name: Check assets/javascripts/issue_templates.js is up-to-date

on:
  pull_request:

permissions:
  contents: read

jobs:
  check-asset-js:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.16.0

      - name: Install dependencies
        run: npm ci

      - name: Rebuild the assets/javascripts/issue_templates.js
        run: npm run build

      - name: Compare the expected and actual assets/javascripts/issue_templates.js
        run: |
          if [ "$(git diff --ignore-space-at-eol assets/javascripts/ | wc -l)" -gt "0" ]; then
            cat <<MSG
              assets/javascripts/issue_templates.js is out of date.
              Please build and push again according to the "6. Building Scripts" section in README.md.
            MSG
            exit 1
          fi
